version: "3"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    container_name: flask_app
    environment:
      FLASK_APP: "app/index.py"
      FLASK_ENV: "development"
    command: "flask run --host=0.0.0.0 --port=5000"
    networks:
        - webapp-network
networks:
    webapp-network:
        external: true